# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  projectPath: 'src/App/App.csproj'

steps:
- script: dotnet build --configuration $(buildConfiguration) $(projectPath)
  displayName: 'dotnet build $(buildConfiguration)'
- script: |
    dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./TestResults/Coverage/ /p:Exclude=\"[xunit*]*,[App*]Auto*\" --logger trx
  displayName: 'dotnet tests'
- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
  displayName: 'publish tests'
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: '**/*.xml'
  displayName: 'publish coverage'
- script: |
    docker build -f src/App/arm.dockerfile -t ramosisw/dotnet-hwm:arm .
    docker build -f src/App/amd64.dockerfile -t ramosisw/dotnet-hwm:amd64 .
  displayName: 'docker build arm & amd64'
- script: |
    docker login --username $env:DOCKER_ID --password $env:DOCKER_PSWD
    docker push ramosisw/dotnet-hwm:arm
    docker push ramosisw/dotnet-hwm:amd64
    docker logout
  env:
    DOCKER_ID: $(dockerid)
    DOCKER_PSWD: $(dockerpswd)
  displayName: 'docker push images'
  

